# Docker Compose for Maven Tools MCP Server
# This provides an easy way to run the MCP server with pre-built images

services:
  maven-tools-mcp:
    image: arvindand/maven-tools-mcp:latest
    container_name: maven-tools-mcp
    
    # MCP uses stdio transport, so we need interactive mode
    stdin_open: true
    tty: true
    
    # Network access for Maven Central API
    network_mode: "bridge"
      # Environment variables for configuration
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MAVEN_CENTRAL_TIMEOUT=PT15S
      - MAVEN_CENTRAL_MAX_RESULTS=100
      
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "java", "-version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
