# Docker Compose for Maven Tools MCP Server
# This provides an easy way to run the MCP server with pre-built images

services:
  maven-tools-mcp:
    image: arvindand/maven-tools-mcp:latest
    container_name: maven-tools-mcp
    
    # MCP uses stdio transport - stdin_open required, tty should be false
    stdin_open: true
    tty: false  # Changed: tty interferes with JSON-RPC stdio
    
    # Network access for Maven Central API
    network_mode: "bridge"
    
    # Environment variables for configuration
    environment:
      - SPRING_PROFILES_ACTIVE=docker