# Web profile configuration - enables servlet and actuator endpoints
# Activate with: --spring.profiles.active=web or SPRING_PROFILES_ACTIVE=web
spring:
  main:
    web-application-type: servlet  # Enable web server for actuator

server:
  port: ${SERVER_PORT:8081}  # Configurable port, defaults to 8081

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,caches
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
  health:
    circuitbreakers:
      enabled: true

# Enhanced logging for web profile
logging:
  level:
    "[com.arvindand.mcp.maven]": INFO
    "[io.github.resilience4j]": DEBUG
    "[org.springframework.ai.mcp]": WARN
    "[org.springframework.boot]": WARN
    "[org.springframework]": WARN
    root: WARN
